# Dockerfile for .NET Core Producer
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY *.csproj .
RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/runtime:7.0
WORKDIR /app
COPY --from=build /app .

# Copiar el directorio de archivos JSON en el contenedor
COPY ./json_files ./json_files

ENTRYPOINT ["dotnet", "dotnet_producer.dll"]